# Generated by Django 3.2.5 on 2021-07-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(
                    'AGUARDANDO', 'Aguardando autorização'), ('EM_VISITA', 'em vsita'),
                    ('FINALIZADO', 'Visita finalizada')], default='AGUARDANDO', max_length=10, verbose_name='Status')),
                ('nome_complete', models.CharField(max_length=194, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('numero_casa', models.CharField(max_length=3, verbose_name='Numero da casa a ser visiatada')),
                ('placa_veiculo', models.CharField(
                    blank=True, max_length=7, null=True, verbose_name='Placa do veiculo')),
                ('horario_chegada', models.DateTimeField(
                    auto_now_add=True, verbose_name='Horario de chegada na portaria')),
                ('horario_saida', models.DateTimeField(
                    blank=True, null=True, verbose_name='Horario de saida na portaria')),
                ('horario_autorizacao', models.DateTimeField(
                    blank=True, null=True, verbose_name='Horario da autorização de entrada')),
                ('morador_responsavel', models.CharField(
                    blank=True, max_length=194, null=True,
                    verbose_name='Nome do morador reponsavel por autorizar a entrada do visitante')),
                ('registrado_por', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='porteiros.porteiro',
                    verbose_name='Porteiro responsavel pelo registro')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
    ]
